-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid,
  date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL,
  location text,
  clock_in text,
  clock_out text,
  hours text,
  proof_url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  clock_in_time timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid UNIQUE,
  company_name text NOT NULL,
  setup_completed boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  industry text,
  logo_url text,
  company_email text,
  company_phone text,
  super_admin_name text,
  super_admin_personal_email text,
  super_admin_role text,
  super_admin_avatar_url text,
  super_admin_bio text,
  super_admin_phone text,
  custom_fields jsonb DEFAULT '[]'::jsonb,
  geofencing_enabled boolean DEFAULT true,
  company_lat double precision,
  company_lng double precision,
  company_radius integer DEFAULT 200,
  company_address text,
  shift_start text DEFAULT '09:00'::text,
  shift_end text DEFAULT '18:00'::text,
  working_days ARRAY DEFAULT ARRAY['Mon'::text, 'Tue'::text, 'Wed'::text, 'Thu'::text, 'Fri'::text],
  grace_period_mins integer DEFAULT 15,
  ip_lock_enabled boolean DEFAULT false,
  ip_lock_address text,
  selfie_verification boolean DEFAULT true,
  auto_overtime boolean DEFAULT true,
  attendance_config jsonb DEFAULT '{}'::jsonb,
  custom_roles jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT company_settings_pkey PRIMARY KEY (id),
  CONSTRAINT company_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES auth.users(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_company_id_fkey FOREIGN KEY (company_id) REFERENCES auth.users(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  department_id uuid,
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'Employee'::text,
  is_head boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  avatar_url text,
  emp_id text,
  job_type text,
  phone_number text,
  mobile text,
  address text,
  emergency_contact_name text,
  emergency_contact_number character varying,
  emergency_contact_relation character varying,
  medical_information text,
  account_holder_name text,
  bank_name text,
  account_number character varying,
  ifsc_code character varying,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  blood_group character varying,
  country character varying,
  state character varying,
  city character varying,
  date_of_birth date,
  aadhar_number character varying,
  pan_number character varying,
  aadhar_proof_url text,
  pan_proof_url text,
  education_details jsonb DEFAULT '{"courses": [], "schools": [], "universities": []}'::jsonb,
  insurance_type character varying,
  policy_provider character varying,
  policy_start_date date,
  policy_end_date date,
  coverage_amount numeric,
  nominee_name character varying,
  nominee_relation character varying,
  employee_insurance_id character varying,
  emergency_contact_address text,
  salary numeric,
  shift_type character varying,
  overtime_applicable boolean DEFAULT false,
  claims_applicable boolean DEFAULT false,
  date_of_joining date,
  employment_status character varying,
  job_role character varying,
  site_id uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES auth.users(id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id text NOT NULL,
  sender_id uuid,
  text text,
  type text DEFAULT 'text'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text DEFAULT 'info'::text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);