create table public.employees (
  id uuid not null default gen_random_uuid (),
  company_id uuid null,
  department_id uuid null,
  user_id uuid null,
  name text not null,
  email text not null,
  role text not null default 'Employee'::text,
  designation text null,
  gender text null,
  is_head boolean null default false,
  is_active boolean null default true,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  avatar_url text null,
  emp_id text null,
  job_type text null,
  preferred_name text null,
  personal_email text null,
  date_of_birth date null,
  nationality character varying null,
  country_of_residence character varying null,
  residential_status character varying null,
  nric_number character varying null,
  nric_front_url text null,
  nric_back_url text null,
  cpf_number character varying null,
  tax_identification_number character varying null,
  fin_number character varying null,
  passport_number character varying null,
  passport_expiry_date date null,
  issuing_country character varying null,
  work_pass_type character varying null,
  work_pass_number character varying null,
  work_pass_issue_date date null,
  work_pass_expiry_date date null,
  fin_card_url text null,
  passport_copy_url text null,
  work_pass_copy_url text null,
  mobile text null,
  phone_number text null,
  address text null,
  postal_code character varying(6) null,
  emergency_contact_name text null,
  emergency_contact_number character varying null,
  emergency_contact_relation character varying null,
  emergency_contact_address text null,
  education_details jsonb null default '{"schooling": [], "higher_education": []}'::jsonb,
  certifications jsonb null default '[]'::jsonb,
  insurance_details jsonb null default '[]'::jsonb,
  bank_name text null,
  account_holder_name text null,
  account_number character varying null,
  bank_swift_code character varying null,
  salary numeric null,
  shift_type character varying null,
  overtime_applicable boolean null default false,
  claims_applicable boolean null default false,
  date_of_joining date null,
  employment_status character varying null,
  job_role character varying null,
  site_id uuid null,
  custom_fields jsonb null default '{}'::jsonb,
  blood_group character varying(10) null,
  fcm_token text null,
  current_address text null,
  current_postal_code text null,
  current_email text null,
  current_mobile text null,
  current_mobile_code text null default '+65'::text,
  native_mobile text null,
  native_mobile_code text null,
  constraint employees_pkey primary key (id),
  constraint employees_company_id_fkey foreign KEY (company_id) references auth.users (id),
  constraint employees_department_id_fkey foreign KEY (department_id) references departments (id) on delete CASCADE,
  constraint employees_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;
--as of 6-6-2025 sql code updates--