-- Multi-Phase Employee Setup Data Expansion Patch

ALTER TABLE public.employees
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS emergency_contact_relation VARCHAR(50),
ADD COLUMN IF NOT EXISTS medical_information TEXT,
ADD COLUMN IF NOT EXISTS blood_group VARCHAR(5),
ADD COLUMN IF NOT EXISTS account_holder_name TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS account_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS aadhar_proof_url TEXT,
ADD COLUMN IF NOT EXISTS pan_proof_url TEXT,
ADD COLUMN IF NOT EXISTS education_details JSONB DEFAULT '{"schools":[], "universities":[], "courses":[]}'::jsonb,
ADD COLUMN IF NOT EXISTS insurance_type VARCHAR(100),
ADD COLUMN IF NOT EXISTS policy_provider VARCHAR(100),
ADD COLUMN IF NOT EXISTS policy_start_date DATE,
ADD COLUMN IF NOT EXISTS policy_end_date DATE,
ADD COLUMN IF NOT EXISTS coverage_amount NUMERIC,
ADD COLUMN IF NOT EXISTS nominee_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS nominee_relation VARCHAR(100),
ADD COLUMN IF NOT EXISTS employee_insurance_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS emergency_contact_address TEXT,
ADD COLUMN IF NOT EXISTS salary NUMERIC,
ADD COLUMN IF NOT EXISTS shift_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS overtime_applicable BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS claims_applicable BOOLEAN DEFAULT false;

-- Unique constraints for Email and Mobile are handled dynamically at application layer for logical 'per-company' checks natively avoiding complex Postgres EXCLUDE conditions.
