version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - supabase_network_Xentra

networks:
  supabase_network_Xentra:
    external: true
